# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea3973c18092d9f2c98be4011c1f5502b058c02edcc0697184a38f4938dc45328d61fc9b1b9e5d276cfdf810531a24f69261e1444cb1ed6fa438c7c8fa984da

test:
  secret_key_base: 346b120f98801ff3dcefe728c7d4ab2011820c15425e623fbba88e9ddaa0259452a5c77368a4bcd2b3b2b97bf3dcfc3a352be20dacc34ec72dbf8c9f8c99d9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
